/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.main;

import java.awt.Color;

/**
 *
 * @author cheythi
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        header.setBackground(new Color(255,51,0,180));
        footer.setBackground(new Color(255,51,0,180));
        chooser.setBackground(new Color(0,0,0,180));
        paster.setBackground(new Color(0,0,0,180));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        middle = new javax.swing.JPanel();
        chooser = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        paster = new javax.swing.JPanel();
        paste = new java.awt.TextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        size = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        methods = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        variables = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        inheritance = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        controlStructure = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        coupling = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1140, 598));
        setResizable(false);

        header.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Code Complexity Measurement Tool");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        footer.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        chooser.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout chooserLayout = new javax.swing.GroupLayout(chooser);
        chooser.setLayout(chooserLayout);
        chooserLayout.setHorizontalGroup(
            chooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        chooserLayout.setVerticalGroup(
            chooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setText("Choose file");

        paster.setBackground(new java.awt.Color(102, 102, 102));

        paste.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout pasterLayout = new javax.swing.GroupLayout(paster);
        paster.setLayout(pasterLayout);
        pasterLayout.setHorizontalGroup(
            pasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
            .addGroup(pasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pasterLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(paste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pasterLayout.setVerticalGroup(
            pasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
            .addGroup(pasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pasterLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(paste, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setText("Paste code");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setText("Select type");

        jComboBox1.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "C++" }));

        size.setBackground(new java.awt.Color(204, 204, 204));
        size.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sizeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sizeMouseReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("size");

        javax.swing.GroupLayout sizeLayout = new javax.swing.GroupLayout(size);
        size.setLayout(sizeLayout);
        sizeLayout.setHorizontalGroup(
            sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sizeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        sizeLayout.setVerticalGroup(
            sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sizeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        methods.setBackground(new java.awt.Color(204, 204, 204));
        methods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                methodsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                methodsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                methodsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                methodsMouseReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("methods");

        javax.swing.GroupLayout methodsLayout = new javax.swing.GroupLayout(methods);
        methods.setLayout(methodsLayout);
        methodsLayout.setHorizontalGroup(
            methodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, methodsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        methodsLayout.setVerticalGroup(
            methodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(methodsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        variables.setBackground(new java.awt.Color(204, 204, 204));
        variables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                variablesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                variablesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                variablesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                variablesMouseReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("variables");

        javax.swing.GroupLayout variablesLayout = new javax.swing.GroupLayout(variables);
        variables.setLayout(variablesLayout);
        variablesLayout.setHorizontalGroup(
            variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, variablesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        variablesLayout.setVerticalGroup(
            variablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inheritance.setBackground(new java.awt.Color(204, 204, 204));
        inheritance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inheritanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inheritanceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inheritanceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inheritanceMouseReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("inheritance");

        javax.swing.GroupLayout inheritanceLayout = new javax.swing.GroupLayout(inheritance);
        inheritance.setLayout(inheritanceLayout);
        inheritanceLayout.setHorizontalGroup(
            inheritanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inheritanceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        inheritanceLayout.setVerticalGroup(
            inheritanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inheritanceLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        controlStructure.setBackground(new java.awt.Color(204, 204, 204));
        controlStructure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                controlStructureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                controlStructureMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                controlStructureMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                controlStructureMouseReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("control structures");

        javax.swing.GroupLayout controlStructureLayout = new javax.swing.GroupLayout(controlStructure);
        controlStructure.setLayout(controlStructureLayout);
        controlStructureLayout.setHorizontalGroup(
            controlStructureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlStructureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );
        controlStructureLayout.setVerticalGroup(
            controlStructureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlStructureLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        coupling.setBackground(new java.awt.Color(204, 204, 204));
        coupling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                couplingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                couplingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                couplingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                couplingMouseReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("coupling");

        javax.swing.GroupLayout couplingLayout = new javax.swing.GroupLayout(coupling);
        coupling.setLayout(couplingLayout);
        couplingLayout.setHorizontalGroup(
            couplingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, couplingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );
        couplingLayout.setVerticalGroup(
            couplingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(couplingLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout middleLayout = new javax.swing.GroupLayout(middle);
        middle.setLayout(middleLayout);
        middleLayout.setHorizontalGroup(
            middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middleLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel2)
                .addGap(208, 208, 208)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(255, 255, 255))
            .addGroup(middleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, middleLayout.createSequentialGroup()
                        .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(methods, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(variables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addComponent(chooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(middleLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(paster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(middleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inheritance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(controlStructure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(coupling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        middleLayout.setVerticalGroup(
            middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middleLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(variables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(middleLayout.createSequentialGroup()
                        .addGroup(middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(controlStructure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(coupling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(size, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(methods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inheritance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(middle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(middle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sizeMouseEntered
        size.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_sizeMouseEntered

    private void sizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sizeMouseExited
        size.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_sizeMouseExited

    private void sizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sizeMousePressed
        size.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_sizeMousePressed

    private void sizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sizeMouseReleased
        size.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_sizeMouseReleased

    private void methodsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_methodsMouseEntered
        methods.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_methodsMouseEntered

    private void methodsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_methodsMouseExited
        methods.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_methodsMouseExited

    private void methodsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_methodsMousePressed
        methods.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_methodsMousePressed

    private void methodsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_methodsMouseReleased
        methods.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_methodsMouseReleased

    private void variablesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_variablesMouseEntered
        variables.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_variablesMouseEntered

    private void variablesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_variablesMouseExited
        variables.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_variablesMouseExited

    private void variablesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_variablesMousePressed
        variables.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_variablesMousePressed

    private void variablesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_variablesMouseReleased
        variables.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_variablesMouseReleased

    private void inheritanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inheritanceMouseEntered
        inheritance.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_inheritanceMouseEntered

    private void inheritanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inheritanceMouseExited
        inheritance.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_inheritanceMouseExited

    private void inheritanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inheritanceMousePressed
        inheritance.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_inheritanceMousePressed

    private void inheritanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inheritanceMouseReleased
        inheritance.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_inheritanceMouseReleased

    private void controlStructureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlStructureMouseEntered
        controlStructure.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_controlStructureMouseEntered

    private void controlStructureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlStructureMouseExited
        controlStructure.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_controlStructureMouseExited

    private void controlStructureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlStructureMousePressed
        controlStructure.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_controlStructureMousePressed

    private void controlStructureMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlStructureMouseReleased
        controlStructure.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_controlStructureMouseReleased

    private void couplingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_couplingMouseEntered
        coupling.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_couplingMouseEntered

    private void couplingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_couplingMouseExited
        coupling.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_couplingMouseExited

    private void couplingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_couplingMousePressed
        coupling.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_couplingMousePressed

    private void couplingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_couplingMouseReleased
        coupling.setBackground(new Color(204,255,51));
    }//GEN-LAST:event_couplingMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chooser;
    private javax.swing.JPanel controlStructure;
    private javax.swing.JPanel coupling;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JPanel inheritance;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel methods;
    private javax.swing.JPanel middle;
    private java.awt.TextArea paste;
    private javax.swing.JPanel paster;
    private javax.swing.JPanel size;
    private javax.swing.JPanel variables;
    // End of variables declaration//GEN-END:variables
}
